[project]
name = "piobot"
version = "1.0.2"
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
classifiers = ["Private :: Do Not Upload"]
requires-python = ">=3.12"
dependencies = [
    "gitpython==3.1.59",
    "packaging==26.3",
    "pygithub==2.9.1",
    "requests==2.34.2",
]

[dependency-groups]
dev = ["pytest==9.0.2", "ruff==0.16.3"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true
